[tool.poetry]
name = "regresa"
version = "0.1.0"
description = ""
authors = ["Carlos Capote Pérez-Andreu <carlos.capote@hawara.es>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
numpy = {version = "^1.26.1", python = ">=3.9,<3.13"}
matplotlib = "^3.8.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
